### ISSUE TITLE
专栏下载报错

### ISSUE THREAD

**Issue by jackie88558** [mmzou/geektime-dl#10]
geektime-dl 180

level=fatal msg="open 深入拆解Tomcat & Jetty \\MP3\\开篇词 - Java程序员如何快速成长？.mp4.mp3.download: The system cannot find the path specified."

**Comment by cion-J** [comment]
估计是因为目录包含空格，搞一下源码编译一个。。作者这么久没来看

**Comment by weiyongsheng** [comment]
最近版本已解决该问题，原因是文件夹名结尾有空格（ 73dafcc ）
