### ISSUE TITLE
命令不存在

### ISSUE THREAD

**Issue by o2520** [mmzou/geektime-dl#2]
go get后该执行什么 geektime-dl 命令不存在

**Comment by weiyongsheng** [comment]
@o2520 
- 通过go build在当前目录下生成geektime-dl二进制文件：

```bash
go build -o geektime-dl
```

- 或者通过go install 直接生成geektime-dl命令到$GOPATH/bin目录下

```bash
go install
```

**Comment by zhangzf1996** [comment]
geektime-dl  安装不成功
![image](https://user-images.githubusercontent.com/64057073/79835819-ef117380-83e1-11ea-8f3c-52b090d16add.png)
release下载的二进制文件也没办法安装，直接闪退（windows）

**Comment by weiyongsheng** [comment]
@zhangzf1996 你要将你下载的二进制文件放在你的PATH目录下，然后借助你的终端运行`geektime-dl`命令才可以，暂不支持直接点击打开

**Comment by tangkunyin** [comment]
@zhangzf1996 试试本地安装（go version: go1.14.2 darwin/amd64）
```
git clone  git@github.com:mmzou/geektime-dl.git

cd geektime-dl

go build -o geektime-dl

go install
```

**Comment by xiaoyuqing** [comment]
> @zhangzf1996 试试本地安装（go version: go1.14.2 darwin/amd64）
> 
> ```
> git clone  git@github.com:mmzou/geektime-dl.git
> 
> cd geektime-dl
> 
> go build -o geektime-dl
> 
> go install
> ```

执行了这些还是报命令不存在
![image](https://user-images.githubusercontent.com/14144617/83941389-82312c00-a81d-11ea-9fbe-854b1bdbd438.png)

**Comment by D-R-L** [comment]
> @zhangzf1996 试试本地安装（go version: go1.14.2 darwin/amd64）
> 
> ```
> git clone  git@github.com:mmzou/geektime-dl.git
> 
> cd geektime-dl
> 
> go build -o geektime-dl
> 
> go install
> ```

敲这俩 go build -o geektime-dl
go install
总是显示
go: github.com/cheggaaa/pb@v1.0.25: Get https://proxy.golang.org/github.com/cheggaaa/pb/@v/v1.0.25.mod: dial tcp 34.64.4.17:443: i/o timeout

**Comment by hf007fs** [comment]
D:\>geektime-dl 265
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/mmzou/geektime-dl/downloader.Download(0x2bd2f, 0xc00050cb20, 0x11, 0xaa0069, 0x6, 0x1, 0xc00009c450, 0x0, 0x0, 0x0, ...)
        /home/miaoke/go/src/github.com/mmzou/geektime-dl/downloader/downloader.go:43 +0xb45
github.com/mmzou/geektime-dl/cli/cmds.downloadAction(0xc0001309a0, 0x0, 0xc0001fce20)
        /home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/cmds/download.go:72 +0x6fc
github.com/urfave/cli.HandleAction(0x9d3280, 0xaca0e8, 0xc0001309a0, 0xc0001309a0, 0x0)
        /home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x121
github.com/urfave/cli.Command.Run(0xa9d678, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa9d678, 0x0, 0xa9d678, ...)
        /home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x581
github.com/mmzou/geektime-dl/cli/cmds.DefaultAction(0xc000130840, 0x0, 0x0)
        /home/miaoke/go/src/github.com/mmzou/geektime-dl/cli/cmds/cmds.go:86 +0x10b
github.com/urfave/cli.HandleAction(0x9d3280, 0xaca0c8, 0xc000130840, 0x0, 0x0)
        /home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x121
github.com/urfave/cli.(*App).Run(0xc00015a540, 0xc0000044c0, 0x2, 0x2, 0x0, 0x0)
        /home/miaoke/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:288 +0x650
main.main()
        /home/miaoke/go/src/github.com/mmzou/geektime-dl/main.go:30 +0x4ce
