### ISSUE TITLE
生成某些pdf 失败 FATA[0003] encountered exception 'Uncaught' (1:40) 

### ISSUE THREAD

**Issue by Chocogo** [mmzou/geektime-dl#25]
已经下载完，在生成pdf阶段，前面能成功生成pdf，到某个章节就报错了，然后后面一直都是失败的直到结束，正在生成文件：【39 - 回溯算法：从电影《蝴蝶效应》中学习回溯算法的核心思想.pdf】 失败
FATA[0003] encountered exception 'Uncaught' (1:40)

**Comment by neorat** [comment]
请教下你是在win10_64位的系统上操作的吗？chromedp有安装吗？我直接下载release的exe版本，每次下载时都是失败，会唤起页面，但是url是空的。后来修改源代码，配置了个chromedp.ExecPath(`C:\Program Files (x86)\Google\Chrome\Application\chrome.exe`)。可以打开相应的专栏页面，但是无法下载。网上搜索解决方案说需要headless。待解决中...

**Comment by Chocogo** [comment]
我用的是mac 。。就本来有chorme，装完go后配置了一下环境变量，然后就可以直接下载了。。。然后下午重新执行了一下，发现早上的FATA[0003] encountered exception 'Uncaught' (1:40)不见了，已经能成功下载了。。。不知道是不是网络的原因还是因为我装了FFmpeg（我是最后要下视频才装FFmpeg的）。。

**Comment by magictour** [comment]
请问这个怎么解决的？
