### ISSUE TITLE
这是什么意思。？

### ISSUE THREAD

**Issue by hcliu987** [mmzou/geektime-dl#30]
![image](https://user-images.githubusercontent.com/52879991/85293742-5b871c80-b4d0-11ea-8466-2508c389661d.png)
mac os   go 版本1.14.4

**Comment by weiyongsheng** [comment]
urfave/cli 版本问题
解决办法：https://github.com/mmzou/geektime-dl/issues/21#issuecomment-635455406

**Comment by hcliu987** [comment]
谢谢搞定
