### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by NasserGo** [mmzou/geektime-dl#5]
当课程中没有视频也没有mp3的时候，就会下载失败，跳过
这样所有pdf就不会生成下载。

情况：最后5课没有mp3，下载mp3时，到这里就失败中断了，不会跳过失败的，去生成pdf
![image](https://user-images.githubusercontent.com/13278804/80581275-83618300-8a3f-11ea-9347-624969ede00e.png)
![image](https://user-images.githubusercontent.com/13278804/80581305-8e1c1800-8a3f-11ea-9f22-bc2fbd25c943.png)

**Comment by weiyongsheng** [comment]
此bug已修复，谢谢提醒！

commit 1f208c2

**Comment by NasserGo** [comment]
哇，太感谢了🙏， 正在学习源码
