### ISSUE TITLE
win10无法生成PDF

### ISSUE THREAD

**Issue by yunchenran** [mmzou/geektime-dl#54]
全是报错，可不可以指定命令不要生成PDF呢？

正在生成文件：【[37;1m开篇词 - 跑步，不那么简单的事儿.pdf[0m】 [31;1m失败2, err=context deadline exceeded[0m
正在生成文件：【[37;1m01 - 跑两步就喘了，是不是我不适合跑步？.pdf[0m】 [31;1m失败2, err=context deadline exceeded[0m
正在生成文件：【[37;1m02 - 正确的跑步姿势是什么样的？.pdf[0m】

**Comment by weiyongsheng** [comment]
该问题最新版本已经修复了。
