### ISSUE TITLE
下载报错：unknown PrivateNetworkRequestPolicy value

### ISSUE THREAD

**Issue by googlemeoften** [mmzou/geektime-dl#66]
2022/02/28 18:27:48 ERROR: could not unmarshal event: unknown PrivateNetworkRequestPolicy value
2022/02/28 18:27:48 ERROR: could not unmarshal event: unknown PrivateNetworkRequestPolicy value
2022/02/28 18:27:48 ERROR: could not unmarshal event: unknown PrivateNetworkRequestPolicy value

**Comment by yizems** [comment]
修改源码
修改下这两个的版本号即可

```
	github.com/chromedp/cdproto v0.0.0-20220228194516-ead8cf59b1fa
	github.com/chromedp/chromedp v0.7.7
```

**Comment by GreeyiSaEs** [comment]
> 修改源码 修改下这两个的版本号即可
> 
> ```
> 	github.com/chromedp/cdproto v0.0.0-20220228194516-ead8cf59b1fa
> 	github.com/chromedp/chromedp v0.7.7
> ```

下载pdf内容为空请问怎么解决呀

**Comment by yizems** [comment]
修改源码, 加延时, 增加延时, 顺便在下载pdf 之前, 都等待10秒, 因为 有限流策略

**Comment by weiyongsheng** [comment]
> > 修改源码 修改下这两个的版本号即可
> > ```
> > 	github.com/chromedp/cdproto v0.0.0-20220228194516-ead8cf59b1fa
> > 	github.com/chromedp/chromedp v0.7.7
> > ```
> 
> 下载pdf内容为空请问怎么解决呀

下载pdf内容为空请的问题已经修复了，重新下载即可。
