### ISSUE TITLE
生成的PDF内容为空

### ISSUE THREAD

**Issue by GreeyiSaEs** [mmzou/geektime-dl#67]
生成的PDF内容为空

**Comment by kaiarvin** [comment]
![image](https://user-images.githubusercontent.com/15983118/159120435-b18b9a01-0a3e-4b24-b8cb-f5f88b69e262.png)
utils包下面的chromedp.go文件中有个ColumnPrintToPDF函数，在chromedp.Run里面重新设置一下chromedp.Emulate和navigateAndWaitFor的参数，我选用的是chromedp.Emulate(device.KindleFireHDX)，navigateAndWaitFor(`https://time.geekbang.org/column/article/`+strconv.Itoa(aid), "firstImagePaint"),重新打包之后可以生成图片

**Comment by weiyongsheng** [comment]
问题已经修复了，重新下载即可。
