### ISSUE TITLE
489 专栏资源下载出错

### ISSUE THREAD

**Issue by wajika** [mmzou/geektime-dl#72]
>geektime-dl 489
开篇词 - 做性价比最高的自动化测试 13.97 MiB / 13.97 MiB [======================================] 100.00% 15.84 MiB/s 0s
01｜ROI价值内核 自动化测试的价值可以量化么？ 19.56 MiB / 19.56 MiB [===========================] 100.00% 18.98 MiB/s 1s
02｜3KU法则 如何找出最优自动化实施截面？ 16.42 MiB / 16.42 MiB [===============================] 100.00% 13.90 MiB/s 1s
03｜工具选择 什么工具框架值得用？ 15.69 MiB / 15.69 MiB [======================================] 100.00% 14.84 MiB/s 1s
04｜脚本复用 什么样的代码才值得写？ 16.70 MiB / 16.70 MiB [====================================] 100.00% 14.53 MiB/s 1s
05｜Auto Gen Auto 所有测试工作即代码 16.20 MiB / 16.20 MiB [===================================] 100.00% 13.32 MiB/s 1s
06｜左移&右移 测试如何在Dev和Ops领域大展身手？ 13.31 MiB / 13.31 MiB [=========================] 100.00% 10.54 MiB/s 1s
07｜需求提炼（一） 单体应用要测什么？ 13.40 MiB / 13.40 MiB [==================================] 100.00% 12.83 MiB/s 1s
08｜需求提炼（二） 微服务集群要测什么？ 13.59 MiB / 13.59 MiB [================================] 100.00% 11.80 MiB/s 1s
09｜3KU法则 为一个订餐系统设计全栈测试方案 10.64 MiB / 10.64 MiB [=============================] 100.00% 10.96 MiB/s 0s
正在生成文件：【[37;1m开篇词 - 做性价比最高的自动化测试.pdf[0m】 [32;1m完成[0m
正在生成文件：【[37;1m01｜ROI价值内核 自动化测试的价值可以量化么？.pdf[0m】 [32;1m完成[0m
正在生成文件：【[37;1m02｜3KU法则 如何找出最优自动化实施截面？.pdf[0m】 [32;1m完成[0m
正在生成文件：【[37;1m03｜工具选择 什么工具框架值得用？.pdf[0m】 [32;1m完成[0m
正在生成文件：【[37;1m04｜脚本复用 什么样的代码才值得写？.pdf[0m】 [32;1m完成[0m
正在生成文件：【[37;1m05｜Auto Gen Auto 所有测试工作即代码.pdf[0m】 [31;1m失败2, err=exception "Uncaught" (1:39): TypeError: Cannot read properties of null (reading 'parentElement')
    at <anonymous>:2:40[0m
正在生成文件：【[37;1m06｜左移&右移 测试如何在Dev和Ops领域大展身手？.pdf[0m】 [31;1m失败2, err=exception "Uncaught" (1:39): TypeError: Cannot read properties of null (reading 'parentElement')
    at <anonymous>:2:40[0m
正在生成文件：【[37;1m07｜需求提炼（一） 单体应用要测什么？.pdf[0m】 [31;1m失败2, err=exception "Uncaught" (1:39): TypeError: Cannot read properties of null (reading 'parentElement')
    at <anonymous>:2:40[0m
正在生成文件：【[37;1m08｜需求提炼（二） 微服务集群要测什么？.pdf[0m】 [31;1m失败2, err=exception "Uncaught" (1:39): TypeError: Cannot read properties of null (reading 'parentElement')
    at <anonymous>:2:40[0m
正在生成文件：【[37;1m09｜3KU法则 为一个订餐系统设计全栈测试方案.pdf[0m】 [31;1m失败2, err=exception "Uncaught" (1:39): TypeError: Cannot read properties of null (reading 'parentElement')
    at <anonymous>:2:40[0m
time="2022-04-08T09:57:13+08:00" level=fatal msg="exception \"Uncaught\" (1:39): TypeError: Cannot read properties of null (reading 'parentElement')\n    at <anonymous>:2:40"

**Comment by L-Super** [comment]
同遇到这个报错，请问最后解决了吗

**Comment by wajika** [comment]
> 同遇到这个报错，请问最后解决了吗

没有

**Comment by L-Super** [comment]
我遇到这个问题后，重写登录账号，再下载就好了。不过这过程，经常需要反复登录下载

**Comment by wajika** [comment]
> 我遇到这个问题后，重写登录账号，再下载就好了。不过这过程，经常需要反复登录下载

好的，我有空再试试
