### ISSUE TITLE
如何使用ffmpeg 整合下载好的视频分片文件

### ISSUE THREAD

**Issue by shenzhim** [mmzou/geektime-dl#9]
使用geektime-dl 下载好后，在执行 ffmpeg时 发现本地没有安装 导致执行失败了。

后来重新安装了ffmpeg了，现在执行 ffmpeg的什么命令 可以对 下载好的视频分片文件 进行整合呢

**Comment by weiyongsheng** [comment]
命令如下：
```bash
ffmpeg -y -f concat -safe -1 -i xxx.txt  -c copy -bsf:a aac_adtstoasc xxx.mp4
```
- `xxx.txt`：在当前目录下的txt文档，包含了已下载完成待合并的`ts`文件
- `xxx.mp4`：要合并成的mp4文件名

可查看：https://stackoverflow.com/questions/32528595/ffmpeg-mp4-from-http-live-streaming-m3u8-file
